function init(self)
	self.rot = go.get_rotation()
	self.speed = 800
	self.velocity = vmath.rotate(self.rot, vmath.vector3(0, self.speed, 0))
	self.d = 0
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.velocity * dt
	self.d = self.d + self.speed * dt
	go.set_position(pos)
	
	if self.d > 570 then
		go.delete()
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		go.delete()
	end
end
